version: '3'
services:
  db:
    container_name: postgres_db_labreport
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=labreport_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: labreport_app
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "6060:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/labreport_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
  db:

