version: '3.9'

services:
  db:
    image: mysql:8.0
    command: --authentication_policy=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd1
      MYSQL_DATABASE: lab-report-mysql
      MYSQL_USER: test-user
      MYSQL_PASSWORD: userpasswd1
    ports:
      - "3306:3306"
  app:
    image: 'lab-report-api:latest'
    build:
      context: .
    container_name: lab-report-api
    ports:
      - "9090:8080"

