version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --authentication_policy=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ubo11361
      MYSQL_DATABASE: labreport
      MYSQL_USER: ubovic
      MYSQL_PASSWORD: ubovic11361
    ports:
      - "3306:3306"
